version: "3"
services:
  demoapp:
    build: .
    depends_on:
      - server
      - database
  
  database:
    image: redis:latest
  
  server:
    image: nginx:latest
    volumes:
      - ./conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
