services:
 demoapp:
  build: .

 database:
  image: redis:latest
  container_name: redis
  volumes:
   - redis_data:/data
  ports:
   - 6379:6379
    
 server:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
    restart: always


volumes:
 redis_data:
